### PR TITLE
Improve scroll position test

### PR DESCRIPTION
**Pull request by cesarvarela**
Should be much less flaky

### CODE REVIEW

**Comment by smcgregor** [comment]
@cesarvarela should I merge this, or does the `WIP` description mean I should wait?

**Comment by cesarvarela** [comment]
@smcgregor, yes, the `wip` meant that it wasn't ready; it is now.

**Comment by smcgregor** [comment]
Because you tested it more? I don't see new commits.

**Comment by cesarvarela** [comment]
Yes, I wanted to test it a bit more.

**Pull request merged**
