### PR TITLE
Replace react-c3 with react-billboard

### PR DESCRIPTION
**Pull request by cesarvarela**
Part of #243

### CODE REVIEW

**Comment by smcgregor** [comment]
I think maybe you need to merge master into this branch?

**Comment by cesarvarela** [comment]
@smcgregor updated, the build is failing but I think the reason it is not related to the PR.

**Comment by smcgregor** [comment]
Build is passing at the moment on master. Does it work for you on local? My best guess is that the package lock needs to be updated after merging master in since both involve package updates.

**Comment by cesarvarela** [comment]
@smcgregor it's working now 🎉

**Comment by smcgregor** [comment]
Deploy preview shows a blank screen and `TypeError: Cannot read property 'width' of undefined` in the console.

**Comment by cesarvarela** [comment]
There were some facets with an empty label/value. I'm setting the blank labels to `N/A` lmk if you want to keep that or filter them out.

image

**Comment by cesarvarela** [comment]
Just noticed that it looks empty here too:

image

**Comment by smcgregor** [comment]
"NA" means "not applicable", which may not be the case in some instances. I think this should be fixed in the backend, or labeled as "not assigned". I am not sure why that one case is rendering with zero incidents. It should only render things that have values/counts.

**Comment by cesarvarela** [comment]
Ok, I've added a filter to remove empty facets so we can merge this and fix the backend stuff later.

**Pull request merged**
