### PR TITLE
Feature e2e login roles

### PR DESCRIPTION
**Pull request by cesarvarela**
To get this to work 2 new env variables need to be added:

`E2E_ADMIN_USERNAME` and `E2E_ADMIN_PASSWORD`

As the name implies this should belong to a user with the admin role.

builds on top of #390  and #389

### CODE REVIEW

**Comment by smcgregor** [comment]
@cesarvarela can you resolve the merge conflict here?

**Comment by cesarvarela** [comment]
Updated.

Tests are failing here because the preview url isn't whitelisted.

**Comment by smcgregor** [comment]
@cesarvarela Can you document the new environment variables in the readme? Also, this is looking more like something that will require having a test environment for the production branch that is separate from the production environment.

**Comment by smcgregor** [comment]
@cesarvarela build is failing, do I need to make changes to the build environment?

**Comment by cesarvarela** [comment]
Merged staging and it is passing now, I'll fix the failing tests in a separate pr.

**Pull request merged**
