### PR TITLE
Update to Gatsby v3

### LINKED ISSUE #195: Upgrade to Gatsby V3

### PR DESCRIPTION
**Pull request by cesarvarela**
This was quite an adventure, but I think everything is working.

(There are a few warnings that I would like to fix in another PR that are best practices that gatsby didn't report in v2.)

Also, there is still a Flash Of Unstyled Content that I thought would get fixed with this but still is there. It will need deeper investigation.

closes #195

### CODE REVIEW

**Comment by smcgregor** [comment]
Build time on the core update is roughly the same as the prior version. It is sitting at `Build time: 3m 52s. Total deploy time: 4m 5s`. I think the long deploy time is likely due to the LFS image hosting, which adds more reason to move image hosting off of git lfs. I still class this as "tomorrow's problem".

I am going to run this branch locally and make sure it is good from the developer perspective. @cesarvarela if that shows well, are you 👍 for me merging and deploying this to production? I don't want this hanging around too long since it is likely to cause issues in the other PRs.

**Comment by smcgregor** [comment]
Is there any trick to getting this updated locally? A migration guide? When I attempt to install the dependencies locally, I get the following:
```
(base) computer:gatsby-site sean$ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: @babel/core@7.12.9
npm ERR! node_modules/@babel/core
npm ERR!   @babel/core@"7.12.9" from @mdx-js/mdx@1.6.22
npm ERR!   node_modules/@mdx-js/mdx
npm ERR!     @mdx-js/mdx@"^1.6.22" from the root project
npm ERR!     @mdx-js/mdx@"1.6.22" from @mdx-js/loader@1.6.22
npm ERR!     node_modules/@mdx-js/loader
npm ERR!       @mdx-js/loader@"^1.6.22" from the root project
npm ERR!     1 more (gatsby-plugin-mdx)
npm ERR!   @babel/core@"7.12.9" from remark-mdx@1.6.22
npm ERR!   node_modules/remark-mdx
npm ERR!     remark-mdx@"1.6.22" from @mdx-js/mdx@1.6.22
npm ERR!     node_modules/@mdx-js/mdx
npm ERR!       @mdx-js/mdx@"^1.6.22" from the root project
npm ERR!       2 more (@mdx-js/loader, gatsby-plugin-mdx)
npm ERR!   16 more (@emotion/css, @emotion/react, @emotion/styled, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @babel/core@"^7.13.0" from @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@7.14.5
npm ERR! node_modules/@babel/preset-env/node_modules/@babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining
npm ERR!   @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@"^7.14.5" from @babel/preset-env@7.14.8
npm ERR!   node_modules/@babel/preset-env
npm ERR!     @babel/preset-env@"^7.14.7" from babel-preset-gatsby@1.10.0
npm ERR!     node_modules/gatsby/node_modules/babel-preset-gatsby
npm ERR!       babel-preset-gatsby@"^1.10.0" from gatsby@3.10.1
npm ERR!       node_modules/gatsby
npm ERR!     1 more (gatsby-plugin-mdx)
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

I also tried an NPM update and received a React version conflict for the c3js react library which has not added version 17 support.

**Comment by cesarvarela** [comment]
Yeah, `gatsby clean` and probably deleting `node_modules` and installing again.

**Comment by smcgregor** [comment]
Much the same with a `gatsby clean` and removing node_modules.
```
(base) computer:gatsby-site sean$ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: gatsby-gitbook-aiid@0.2.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.5.0 || ^16.0.0" from react-c3js@0.1.20
npm ERR! node_modules/react-c3js
npm ERR!   react-c3js@"^0.1.20" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```
It looks like react 17 is indeed not supported by `react-c3js`. Did you force the installation through? I don't see how this could have worked.

**Comment by cesarvarela** [comment]
I think it might be that you have an old `package-lock.json`?

The consensus seems to be that it should be committed, not sure why that's not the case? (Other than locking people into either `npm` or `yarn`)

**Comment by smcgregor** [comment]
Same result when removing the lock file.

**Comment by cesarvarela** [comment]
Weird, I tried locally with npm in a repo I just cloned and it worked.

Just in case but have you tried with yarn? Also, can you see what is Netlify using? Seems to not have trouble.

**Comment by smcgregor** [comment]
I just did a fresh clone from master and even on master I am getting dependency issues... This is starting to look like I need to burn it all down and start my environment over. Can you share any details that may save me the trouble? Maybe your package lock?

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: graphql@14.7.0
npm ERR! node_modules/graphql
npm ERR!   graphql@"^14.7.0" from the root project
npm ERR!   graphql@"^14.6.0" from gatsby@2.32.13
npm ERR!   node_modules/gatsby
npm ERR!     gatsby@"^2.32.11" from the root project
npm ERR!     peer gatsby@"^2.0.0" from gatsby-plugin-catch-links@2.10.0
npm ERR!     node_modules/gatsby-plugin-catch-links
npm ERR!       gatsby-plugin-catch-links@"^2.10.0" from the root project
npm ERR!     19 more (gatsby-plugin-emotion, gatsby-plugin-feed, ...)
npm ERR!   25 more (eslint-plugin-graphql, express-graphql, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer graphql@"^15.4.0" from @n1ru4l/graphql-live-query@0.7.1
npm ERR! node_modules/@graphql-tools/url-loader/node_modules/@n1ru4l/graphql-live-query
npm ERR!   @n1ru4l/graphql-live-query@"0.7.1" from @graphql-tools/url-loader@7.0.3
npm ERR!   node_modules/@graphql-tools/url-loader
npm ERR!     @graphql-tools/url-loader@"^7.0.2" from graphql-config@3.4.0
npm ERR!     node_modules/graphql-config
npm ERR!       graphql-config@"^3.0.2" from eslint-plugin-graphql@4.0.0
npm ERR!       node_modules/eslint-plugin-graphql
```

**Comment by cesarvarela** [comment]
Added tracking for the `package-lock.json` file, you pull it should work this time 🙏

**Comment by smcgregor** [comment]
OK, running locally now. Before we merge this we need to capture all the remaining issues surfaced by the upgrade. A few troubling outputs are below. @cesarvarela can you open issues for these or address them before merge?

When running `gatsby develop`
```
warn 
aiid/site/gatsby-site/pages/apps/discover.js
    39:1  warning  In page templates only a default export of a valid React component and the named export of a
page query is allowed.
        All other named exports will cause Fast Refresh to not preserve local component state and do a full
refresh.

        Please move your other named exports to another file. Also make sure that you only export page queries that
 use the "graphql" tag from "gatsby".
  limited-exports-page-templates
    41:1  warning  In page templates only a default export of a valid React component and the named export of a
page query is allowed.
        All other named exports will cause Fast Refresh to not preserve local component state and do a full
refresh.

        Please move your other named exports to another file. Also make sure that you only export page queries that
 use the "graphql" tag from "gatsby".
  limited-exports-page-templates
   437:1  warning  In page templates only a default export of a valid React component and the named export of a
page query is allowed.
        All other named exports will cause Fast Refresh to not preserve local component state and do a full
refresh.

        Please move your other named exports to another file. Also make sure that you only export page queries that
 use the "graphql" tag from "gatsby".
  limited-exports-page-templates
   564:1  warning  In page templates only a default export of a valid React component and the named export of a
page query is allowed.
        All other named exports will cause Fast Refresh to not preserve local component state and do a full
refresh.

        Please move your other named exports to another file. Also make sure that you only export page queries that
 use the "graphql" tag from "gatsby".
  limited-exports-page-templates
   611:1  warning  In page templates only a default export of a valid React component and the named export of a
page query is allowed.
        All other named exports will cause Fast Refresh to not preserve local component state and do a full
refresh.

        Please move your other named exports to another file. Also make sure that you only export page queries that
 use the "graphql" tag from "gatsby".
  limited-exports-page-templates
  1143:1  warning  In page templates only a default export of a valid React component and the named export of a
page query is allowed.
        All other named exports will cause Fast Refresh to not preserve local component state and do a full
refresh.

        Please move your other named exports to another file. Also make sure that you only export page queries that
 use the "graphql" tag from "gatsby".
  limited-exports-page-templates

aiid/site/gatsby-site/src/pages/wordcounts.js
  15:1  warning  In page templates only a default export of a valid React component and the named export of a page
query is allowed.
        All other named exports will cause Fast Refresh to not preserve local component state and do a full
refresh.

        Please move your other named exports to another file. Also make sure that you only export page queries that
 use the "graphql" tag from "gatsby".
  limited-exports-page-templates

✖ 7 problems (0 errors, 7 warnings)
```

When running `gatsby develop`
```
warn the option sizeByPixelDensity is deprecated and should not be used. It will be removed in the next major
release of Gatsby.
```

When running the first npm install.
```
npm WARN deprecated @types/vfile-message@2.0.0: This is a stub types definition. vfile-message provides its own type definitions, so you do not need this installed.
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated apollo-codegen@0.10.13: The 'apollo-codegen' command has been replaced with the more-powerful 'apollo' CLI. Switch to 'apollo' to ensure future updates and visit https://npm.im/apollo#code-generation for more information.
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
```

When visiting `http://localhost:8000/cite/10`
```
react.development.js:220 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `RenderIncidentCards`. See https://reactjs.org/link/warning-keys for more information.
```

**Comment by cesarvarela** [comment]
Yes, I had created #214 for that and now also created #217 and #218.

I'll address them in separate PRs especially #214 that might get a little too big.

**Comment by smcgregor** [comment]
@cesarvarela ok, I don't believe any of these issues will block merge. Do you agree? I don't want to proceed until we are confident the remaining issues will be wrapped fairly quickly.

**Comment by cesarvarela** [comment]
Yeah, I'll close this in favor of #223, which is more up to date with master, and most warnings are fixed too

**Pull request closed without merging**
