### PR TITLE
Automatic Realm deploys

### PR DESCRIPTION
**Pull request by cesarvarela**

### CODE REVIEW

**Comment by smcgregor** [comment]
@cesarvarela this is still marked as draft and you are not requesting review, but when you _are_ requesting review, please include directions on how to set up a staging environment on Realm and I will step through it on a fresh repo checkout for review.

**Comment by cesarvarela** [comment]
@smcgregor Please follow these steps and maybe push the updated files to this branch or send them to my email.

Install realm-cli:
```
npm install -g mongodb-realm-cli
```

Authenticate:
```
realm-cli login --api-key="<my api key>" --private-api-key="<my private api key>"
```

Navigate to `site/realm` and pull the current Realm app
```
 realm-cli pull
```

This should update some files inside the `realm` folder but not all. Let's see how that goes and we can move forward from there.

**Comment by smcgregor** [comment]
@cesarvarela do I do this for a new Realm app, or are you expecting me to do this with production?

**Comment by cesarvarela** [comment]
closing this in favor of #274

**Pull request closed without merging**
