### PR TITLE
Replace Select component with a checkbox group in Taxonomy Form

### PR DESCRIPTION
**Pull request by cesarvarela**
image

The list sometimes gets a little long but gives all the available items visibility. It could be made scrollable with a max height if that's better

part of #455

### CODE REVIEW

**Comment by smcgregor** [comment]
Looks good, except the prompt is no longer accurate (don't use the ctrl key).

**Comment by cesarvarela** [comment]
Removed

**Comment by cesarvarela** [comment]
Maybe do the same but for enum types and using radio buttons instead?

**Comment by smcgregor** [comment]
Yes, sounds like a good change. Should I hold this PR or merge this one first?

**Comment by cesarvarela** [comment]
Yes, let's merge this one as it is.

**Pull request merged**
