### PR TITLE
Map rendering of Location field

### PR DESCRIPTION
**Pull request by cesarvarela**
There needs this env variable to be added with the appropriate value to Netilify:
`GOOGLE_MAPS_API_KEY`

It needs more work to handle `Global`,  `Twitter`, and some other locations, but some early feedback wouldn't hurt.

### CODE REVIEW

**Comment by cesarvarela** [comment]
Once everything is fixed, it should look like this: 

image

**Comment by smcgregor** [comment]
It looks like this needs backend changes?

**Comment by cesarvarela** [comment]
Yes needs a  `GOOGLE_MAPS_API_KEY`env var on Netlify. This key should have access to the  Geocoding API.

**Comment by smcgregor** [comment]
You can presume in the future incidents will either be global or have a specific geographic location (city, country, etc.) that can be geocoded. This visually looks good to me, but I have not been able to play with it live yet.

**Comment by smcgregor** [comment]
Closing in favor of https://github.com/PartnershipOnAI/aiid/pull/394

**Pull request closed without merging**
