### PR TITLE
Add a web archive link component for incident cards

### PR DESCRIPTION
**Pull request by cesarvarela**
The API I'm using is here: https://archive.org/help/wayback_api.php. The component uses the URL and the `date_submitted ` item property to get the Wayback Machine's closest snapshot. If this fails, it falls back to the submitted URL.

It makes the discover page make a lot of requests though, we might want to use an intersection observer to check the link is in view but don't want to over-engineer it either.

This deals with #61

### CODE REVIEW

**Comment by smcgregor** [comment]
Build failed so I can't check the deploy preview.

What is the API's latency? We could capture the click or hover and use the JS API rather than swapping the link target, but this would require fast feedback.

**Comment by cesarvarela** [comment]
Fixed the build. It's quite fast but not fast enough for capturing before the click, I just looked and there won't ever be more than 30 cards per page? Maybe it's not that bad?

What takes way longer is opening the web archive links, but I guess that's expected.

**Comment by smcgregor** [comment]
@cesarvarela please merge master in and I will review the code/merge this. Functionally it is working pretty well.

**Comment by cesarvarela** [comment]
Merged and now uses `window.open` as we discussed.

Another option would be to plug into Gatsby's `onCreateNode` and add a new field on build time to Incident nodes with the report's Web Archive URL.

**Comment by smcgregor** [comment]
Opening the window pending a response from the API is clever. Can you test this in Safari, Chrome, and Firefox to make sure it doesn't run afoul of any security restrictions?

**Comment by cesarvarela** [comment]
Tested:
Windows: Firefox, Chrome, Edge
Ubuntu: Firefox, Chrome
macOS: Safari, Chrome
iOS: Safari, Chrome

Didn't run into any problems  🎈

**Review by smcgregor — APPROVED** [review]

**Pull request merged**
