### PR TITLE
Add roles

### LINKED ISSUE #388: Add User Roles
Add the following roles

* incident_editor
* taxonomy_editor
* taxonomy_editor_cset
* taxonomy_editor_tech
* submitter
* contributor
* wiki

Some of these are likely to be used in the future, but are not for current features.

### PR DESCRIPTION
**Pull request by cesarvarela**
- [x] incident_editor (done in #389)
- [x] taxonomy_editor
- [x] taxonomy_editor_cset
- [x] taxonomy_editor_tech
- [x] submitter

~- [ ] contributor~
~- [ ] wiki~

Closes #388

### CODE REVIEW

**Comment by cesarvarela** [comment]
@smcgregor from the list above, I think the last 2 are not used yet?

**Comment by smcgregor** [comment]
`taxonomy_editor_tech`, `contributor`, and `wiki` are not currently used but are likely to be in the future.

**Comment by cesarvarela** [comment]
Which collections are affected by `contributor` and  wiki `roles`?

**Comment by smcgregor** [comment]
They are not used at the moment. Including them in the list is for future
purposes.

**Pull request merged**
