### PR TITLE
Disable search on loading for discover app

### LINKED ISSUE #149: Making fast changes to instant search form input confuses form
When you type quickly into the instant search form of the discover application, it looks like you sometimes end up in a race condition between different handlers. This is particularly true when you use backspace and pause randomly. The result is that you type into the form before the form programmatically updates to the state that was previously searched, and makes it difficult to efficiently move through the search space. The form should be updated so that it respects what has been entered into the form by the user and does not update to a previously issued search just because there was a delay in getting its response back.

### PR DESCRIPTION
**Pull request by alexmcode**
fixes #149

### CODE REVIEW

**Comment by smcgregor** [comment]
This causes the form element to lose focus and the user needs to click on it again. Can you reset focus after the return?

**Comment by alexmcode** [comment]
@smcgregor it seems to be reproducing only on chrome. I've added an auto-focus and it seems it's working properly. Please let me know

**Comment by smcgregor** [comment]
No change on chrome.

**Comment by alexmcode** [comment]
@smcgregor did another change + some performance changes. let me know if it's still reproducible

**Comment by smcgregor** [comment]
Works well on Chrome and Safari. Merging.

**Pull request merged**
