### PR TITLE
Improve review queue deduplication

### LINKED ISSUE #50: Improve Review Queue - Deduplication
Ingesting new incident reports is burdensome because it is necessary to manually check all new reports for an existing incident identifier. New tools for this process would be useful. Some ideas,

## Publication Date Checks

Incident reports that are published or associated with incident dates near the dates of other incident reports are more likely to be associated with existing incidents in the database

## Text Search

The current review queue does not automatically list incidents that have similar terms. Most document similarity indexing systems would be a good drop in for speeding up the report ingestion.

## Other Ideas

Comment below, but implementation is more valuable than ideas at this time. :)

### PR DESCRIPTION
**Pull request by jt-mchorse**
Closes #50 , #51

### CODE REVIEW

**Comment by smcgregor** [comment]
Can you give more details in your PR descriptions? You have a great many linting changes mixed in here and it is taking me a long time to figure out where the feature changes are, what the functionality is expected to do, etc.

**Comment by jt-mchorse** [comment]
## Lint, Prettier changes
- `format`, `lint` scripts now runs over `src`, `page-creators`, `pages`, `constants` directories.
- Configurations are updated to recognise new alias: `components`, `contexts`, `mongodb`, `pages`, `services`, `templates`, `utils`.
- Object referencing is update: `object["fieldName"]` => `object.fieldName`.

## Package update
- [Fort Awesome](https://fortawesome.com/) has been added to replace unicode with stylish icons in long run.

## Contexts & Hooks
- `useMongo` - provides `runQuery`, `updateOne`. runs default against `review_db`.
- `useUser` - provides current user status: `loading`, `user`, `isAdmin`.
- `MongoContext` - provides `runQuery`, `updateOne` among children.
- `UserContext` - provides user status among children.

## Notable component changes
- `CommunityAuthor`, `GithubLink`, `YoutubeEmbeded` are moved under `src/components`.
- `components/themeProvider.js` has been removed.
- `components/layout.js` and `components/link.js` has been renamed in capital case.
- Form styles and components are moved under `components/Form` to be reused across the site, renamed `CONTAINER` => `FormStyles`, `FORM` => `StyledForm`, `BUTTON` => `StyledButton`
- `src/forms` will be used to keep form components across the site. 
- `submit`, `submitted` pages are updated to use `components/forms/IncidentForm`.

## New Components
- `EditableListItem` -  labeled text can be editable on click.
- `ReadMoreText` - long text expands and collapses on `read more` button click.
- `DBConnecting` -loader to be shown while connecting to DB.
- `Popover` - shortcut to render popover over title

## Feature Changes
- `RelatedIncidents` now show incidents published at the same date to prevent duplication.
- `admins` now can `edit` submitted incidents in review queue by clicking edit button.

**Comment by smcgregor** [comment]
@jt-mchorse it looks like all your commits are going to the deduplication PR, should I close the editing PR?

I also think your edit modal pulled in the CSV import functionality, which is unrelated to the editing functionality.

Screen Shot 2021-03-04 at 9 05 40 PM

**Comment by jt-mchorse** [comment]
@smcgregor , duplication issue has been fixed via #102

**Comment by jt-mchorse** [comment]
https://incidentdatabase.ai/cite/90 now gives right page

**Pull request closed without merging**
