### PR TITLE
add pre-commit hook to apply eslint-fix

### PR DESCRIPTION
**Pull request by jt-mchorse**

### CODE REVIEW

**Comment by smcgregor** [comment]
Did you run into any issues with #57 ? I am worried that this may clear the dependencies cache on netlify and force a solution to #57 before builds will pass again.

**Comment by smcgregor** [comment]
Also, this likely needs a change in the README to let people know what the official linter is.

**Comment by jt-mchorse** [comment]
I just run `npm run build` on `feature/prettier` branch and it succeed without any issues. and as deploy-preview succeeds in check, I doubt there won't be a problem?

Prettier and Eslint were already installed and configured with `format`, `lint` scripts, I just added a pre-commit hook to enforce it. I'll update the Readme.

**Comment by smcgregor** [comment]
Got it. Should one of the checks on GitHub display a report for the linter?

**Comment by jt-mchorse** [comment]
Well, we enforce styling and prevent the commit without proper styling, which means, they can't make a commit, push with lint issues ( at least for the files they've touched ). Of course it helps us to have a report for linter, but I don't think it will benefit us a lot.

**Comment by smcgregor** [comment]
Ah, got it. I'll merge.

**Pull request merged**
