### PR TITLE
Add toast hook

### PR DESCRIPTION
**Pull request by alexmcode**
This PR adds a useToast and uses context to display the toast where we need it

It looks like this:

image

If this is approved, the next step will be to add this through the app. This will probably require some refactoring  - for instance converting some class components into function components

### CODE REVIEW

**Comment by smcgregor** [comment]
This looks good. I think you should add integration with the submit form on the code state in https://github.com/PartnershipOnAI/aiid/pull/166 (if it has not been merged yet). Then I will review it on a working submission case and merge to master.

**Comment by alexmcode** [comment]
Started doing the changes. 

Attention: I've merged `feature-omni` branch into this and changes the destination branch to `feature-omni`. Before merge we should review in what branch this is merged depending on the status of PR #166

**Comment by alexmcode** [comment]
@smcgregor I've added the toast support for submit form in 4 scenarios:
- submit form submitted with success
- submit form submitted report error
- file upload success
- file upload error

Please let me know how the testing went

**Comment by alexmcode** [comment]
@smcgregor fixed the toast and added it to `quickAdd` also.

I also found a bug on this branch: https://github.com/PartnershipOnAI/aiid/pull/173/commits/8757b0afad32cb75807ec3ff825ff3cb925adb3e

please let me know if it's fixed

**Comment by smcgregor** [comment]
Merging this now. My only comment is that links on the success (and potentially other) toasts are not styled appropriate to their background which makes them a bit difficult to read. Functionally the code and playtest I just did are both good.

**Pull request merged**
