### PR TITLE
Clean up QuickAdd page

### PR DESCRIPTION
**Pull request by jt-mchorse**

### CODE REVIEW

**Comment by smcgregor** [comment]
It looks like the app is repeatedly hitting the login endpoint even after it has the logged in context.

**Comment by jt-mchorse** [comment]
This PR contains the changes for making review queue editable only, the login issue has been fixed in next [PR](https://github.com/PartnershipOnAI/aiid/pull/109).

**Comment by jt-mchorse** [comment]
https://user-images.githubusercontent.com/73718225/112171578-2f104600-8bb1-11eb-8a49-ceed3153f807.mov

**Comment by smcgregor** [comment]
Closing in favor of https://github.com/PartnershipOnAI/aiid/pull/100

**Pull request closed without merging**
