### PR TITLE
Relocate stats from discover app to citations page

### PR DESCRIPTION
**Pull request by alexmcode**
This is just a first version to get an idea of the general layout

### CODE REVIEW

**Comment by alexmcode** [comment]
closes #117

**Comment by smcgregor** [comment]
A good start, with obvious needs for cleanup. You can remove the "Back to Discover App" button since people will not always be arriving on the citation pages via the discover app.

**Comment by smcgregor** [comment]
General layout looks good. The containers of each content block needs a bit of work to be visually consistent and clearly delineated, but I think you know that. If you want a more thorough review, please let me know.

**Comment by smcgregor** [comment]
It is functional and well organized. I don't see a reason to update it at the moment and there will be more changes on the page in the future. If you are 👍 , let's move this towards merge.

**Comment by alexmcode** [comment]
All good from my side!

**Comment by smcgregor** [comment]
I merged one of your other MRs and introduced a merge conflict resolved in #127 with these changes.

**Pull request closed without merging**
