### PR TITLE
Add blog

### PR DESCRIPTION
**Pull request by cesarvarela**

### CODE REVIEW

**Comment by smcgregor** [comment]
This broadly looks good to me. A lot of detail work is needed, much of which requires input from me. I'll make a complete review pass of the functionality this week and likely merge it shortly after you update based on the review.

**Comment by smcgregor** [comment]
* Retitle `From the blog` to `Latest Blog Post`
* Individual blog posts should not be in the lefthand navigation. Only `Blog` should be on the left. You can make it a sub item beneath `About`.
* When adding "Blog" to the nav, you accidentally moved the "Welcome to the AIID" nav item to the bottom.
* The bullet list is awkwardly spaced inside the blog post.

```
title: "Blog"
metaTitle: "Meta title here"
metaDescription: "Description here"
```
->
```
title: "AIID Blog"
metaTitle: "AI Incident Database Blog"
metaDescription: "Updates about the developments of the AI Incident Database system"
```

With these changes I think this will be good to go.

**Comment by smcgregor** [comment]
Let's add the date and the name of the author to the blog post itself (so it will more clearly be a blog post), then let's not highlight anything in the nav unless the person is on the blog listing.

**Comment by smcgregor** [comment]
Almost done.

* Let's move the blog preview card on the landing page to below the leaderboard. The prominence the first post was given is temporary.
* The styling between bullets is still awkward (see below)

Screen Shot 2021-07-28 at 9 46 48 PM

**Comment by smcgregor** [comment]
(and please merge master in when you take care of the above, there is a conflict now)

**Comment by cesarvarela** [comment]
Updated both and fixed merge conflicts

**Pull request merged**
