### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by cesarvarela**

### CODE REVIEW

**Comment by smcgregor** [comment]
This looks good to me. The title of the pull request is on updating docs, so both the changes here are OK to group together. I want to note this since in some circumstances these should be separate branches and pull requests. Please clear the "work in progress" flag if you would like me to merge.

**Comment by cesarvarela** [comment]
Yeah, it also gave me trouble when pushing, added an example command to skip the pre-commit hook.

**Comment by smcgregor** [comment]
Merging now. Can you post the message giving you trouble when you try to push without bypassing the hooks?

**Comment by cesarvarela** [comment]
You get asked to enter the credentials for the Netlify app:

```
git push
Username for 'https://<app guid>.netlify.app':
```

There is a long thread about it here:
https://answers.netlify.com/t/git-push-requires-netlify-credentials/12478

It stops happening if you log in to Netlify, but it doesn't seem very new contributor-friendly.

**Pull request merged**
